#Data Encoding
1) Label Encoding
2) One Hot Encoding

In [27]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
data ={"color": ['red', 'green', 'yellow', 'green','red',np.nan]}
df=pd.DataFrame(data)
print("          -original data-          ")
print(df)
print('\n')

#handle null values
df.dropna(inplace=True)
print("          -data after handling null values-          ")
print(df)
print('\n')

print("          -data after label encoding-          ")

#label encoding
le=LabelEncoder()
df['colors_encoder']=le.fit_transform(df['color'])
print(df)
df.drop(["colors_encoder"],axis=1,inplace=True)
print('\n')

print("          -data after one hot encoding-          ")
#one hot encoding(by th help of sklearn)
# encoder = OneHotEncoder()
# encoder_df = encoder.fit_transform(df[["color"]])
# print(encoder_df.toarray())

#one hot encoding(by the help of pandas)
df=pd.get_dummies(df,columns=['color'])
print(df)





          -original data-          
    color
0     red
1   green
2  yellow
3   green
4     red
5     NaN


          -data after handling null values-          
    color
0     red
1   green
2  yellow
3   green
4     red


          -data after label encoding-          
    color  colors_encoder
0     red               1
1   green               0
2  yellow               2
3   green               0
4     red               1


          -data after one hot encoding-          
   color_green  color_red  color_yellow
0        False       True         False
1         True      False         False
2        False      False          True
3         True      False         False
4        False       True         False


In [44]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
data ={"Age":[20,25,np.nan,30,22],
       "Gender":["Male" , "Female" , "Others" , "Male" , "Female"],
       "Name": ["Dheeraj" , "Anjali" , "Ali" , "Kunal" , None]
       }
df=pd.DataFrame(data)
print("          -original data-          ")
print(df)
print('\n')
#handelling missing values
df["Age"] = df["Age"].fillna(df["Age"].mean())
print("          -data after handling missing values-          ")
print(df)
print('\n')
#removing rows with missing values
df.dropna(subset = ["Name"] , inplace = True)
print("          -data after removing rows with missing values-          ")
print(df)
print('\n')
#Label Encoding
le = LabelEncoder()
df["Gender_Encoder"]=le.fit_transform(df["Gender"])
print("          -data after label encoding-          ")
print(df)
print('\n')
df.drop(["Gender_Encoder"],axis=1,inplace=True)
#One Hot Encoding(Using Sklearn)
print("          -data after one hot encoding(Using Sklearn)-          ")
encoder = OneHotEncoder()
encoder_df = encoder.fit_transform(df[["Gender"]])
print(encoder_df.toarray())
print('\n')
#One Hot Encoding(Using Pandas)
df=pd.get_dummies(df,columns=["Gender"])
print("          -data after one hot encoding(Using Pandas)-          ")
print(df)


          -original data-          
    Age  Gender     Name
0  20.0    Male  Dheeraj
1  25.0  Female   Anjali
2   NaN  Others      Ali
3  30.0    Male    Kunal
4  22.0  Female     None


          -data after handling missing values-          
     Age  Gender     Name
0  20.00    Male  Dheeraj
1  25.00  Female   Anjali
2  24.25  Others      Ali
3  30.00    Male    Kunal
4  22.00  Female     None


          -data after removing rows with missing values-          
     Age  Gender     Name
0  20.00    Male  Dheeraj
1  25.00  Female   Anjali
2  24.25  Others      Ali
3  30.00    Male    Kunal


          -data after label encoding-          
     Age  Gender     Name  Gender_Encoder
0  20.00    Male  Dheeraj               1
1  25.00  Female   Anjali               0
2  24.25  Others      Ali               2
3  30.00    Male    Kunal               1


          -data after one hot encoding(Using Sklearn)-          
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


          -data after 