#Sorting In Python


---By Default It Sorts Data Row Wise.

---Axis = 0 Is for Columns'.

---Axis = 1 Is for Rows'.



In [32]:
#sorting in 1D array
print("___Sorting In 1D Array___")
print('\n')
import numpy as np
arr = np.array([10,40,30,90,7,5])
print("--before sorting 1D array--")
print(arr)
arr_s = np.sort(arr)
print("--after sorting 1D array--")
print(arr_s)

print('\n')
print("___Sorting In 2D Array___")
print('\n')

#sorting in 2D array
arr = np.array([[10,40,18,88],[50,99,21,19]])
print("--before sorting 2D array--")
print(arr)
arr_s1 = np.sort(arr)
arr_s2 = np.sort(arr,axis=0)
arr_s3 = np.sort(arr,axis=1)
print("---after sorting---")
print(arr_s1)
print("---after sorting column wise---")
print(arr_s2)
print("---after sorting row wise---")
print(arr_s3)





___Sorting In 1D Array___


--before sorting 1D array--
[10 40 30 90  7  5]
--after sorting 1D array--
[ 5  7 10 30 40 90]


___Sorting In 2D Array___


--before sorting 2D array--
[[10 40 18 88]
 [50 99 21 19]]
---after sorting---
[[10 18 40 88]
 [19 21 50 99]]
---after sorting column wise---
[[10 40 18 19]
 [50 99 21 88]]
---after sorting row wise---
[[10 18 40 88]
 [19 21 50 99]]


Question --> Sort Array In Descending Order

In [26]:
#sort array in descending order
import numpy as np

arr = np.array([10, 20, 40, 7, 99, 1])

print("Original Array:", arr)

arr_s = np.sort(arr)[::-1]   # Reverse the sorted array

print("Descending Order:", arr_s)

Original Array: [10 20 40  7 99  1]
Descending Order: [99 40 20 10  7  1]


#Filter In Array

In [49]:
 #filter in 1D array
import numpy as np
arr = np.array([12,44,56,2,8])
print("--Array--")
print(arr)
print('\n')
arr_f = arr[arr<12]
print("--Filtered Array--")
print(arr_f)

#filter in 2D array
arr = np.array([[12,44,56,2,8],[23,44,56,77,22]])
print("--Array--")
print(arr)
print('\n')
arr_f = arr[arr<77].reshape(3,3)
print("--Filtered Array--")
print(arr_f)



--Array--
[12 44 56  2  8]


--Filtered Array--
[2 8]
--Array--
[[12 44 56  2  8]
 [23 44 56 77 22]]


--Filtered Array--
[[12 44 56]
 [ 2  8 23]
 [44 56 22]]


#Fancy Indexing

In [104]:
#fancy indexing for 1D array
import numpy as np
print("_____In 1D_____")
print('\n')
arr = np.array([20,22,33,10,2])
print("-----Array-----")
print(arr)
arr_F = arr[[1,4,0]]
print('\n')
print("-----Fancy Indexed Array-----")
print(arr_F)

print('\n')
print("_____In 2D_____")
print('\n')
arr = np.array([[20,22,33,10,2],[20,22,33,10,2]])
print("-----Array-----")
print(arr)
print('\n')
print("-----Fancy Indexed Array-----")
arr_F = arr[[[0],[1]],[[2],[4]]]
print(arr_F)

_____In 1D_____


-----Array-----
[20 22 33 10  2]


-----Fancy Indexed Array-----
[22  2 20]


_____In 2D_____


-----Array-----
[[20 22 33 10  2]
 [20 22 33 10  2]]


-----Fancy Indexed Array-----
[[33]
 [ 2]]


#Use Of Where Keyword

In [78]:
#where in 1D array
import numpy as np
print("_____In 1D_____")
print('\n')
arr = np.array([10,20,30,40,50])
print("-----Array-----")
print(arr)
print('\n')
arr_w = np.where(arr<30)#
print("-----Output-----")
print(arr_w)
print('\n')

#example
print("-----Example-----")
print('\n')
arr = np.array([10,18,22,33,41])
print("-----Array-----")
print(arr)
print('\n')
arr_w = np.where(arr>18 , "can vote" , "can't vote")
print("-----Output-----")
print(arr_w)
print('\n')

#where in 2D array
print("_____In 2D_____")
print('\n')
arr = np.array([[12,11,23,3],[45,6,54,43]])
print("-----Array-----")
print(arr)
print('\n')
arr_w = np.where(arr<=22)
print("-----Output-----")
print(arr_w)
print('\n')


_____In 1D_____


-----Array-----
[10 20 30 40 50]


-----Output-----
(array([0, 1]),)


-----Example-----


-----Array-----
[10 18 22 33 41]


-----Output-----
["can't vote" "can't vote" 'can vote' 'can vote' 'can vote']


_____In 2D_____


-----Array-----
[[12 11 23  3]
 [45  6 54 43]]


-----Output-----
(array([0, 0, 0, 1]), array([0, 1, 3, 1]))




#Cancatanation --> Adds Two Arrays

In [95]:
#in 1D array
print("_____In 1D_____")
print('\n')
import numpy as np
arr1 = np.array([12,23,45,55])
arr2 = np.array([10,1,3,55])
print("-----Array 1-----")
print(arr1 )
print('\n')
print("-----Array 2-----")
print(arr2)
print('\n')
print("-----Concatenated Array-----")
print('\n' )

print("_____Sum Of Arrays'_____")
print(arr1+arr2)
print('\n')
#in 2D array
print("_____In 2D_____")
print('\n')
arr1 = np.array([[12,23,45,55],[10,1,3,55]])
arr2 = np.array([[1,2,3,4],[11,34,32,8]])
print("-----Array 1-----")
print(arr1 )
print('\n')
print("-----Array 2-----")
print(arr2)
print('\n')
print("-----Concatenated Array-----")
print('\n' )
arr_c = np.concatenate((arr1,arr2))
print(arr_c)

print('\n')
print("_____Sum Of Arrays'_____")
print(arr1+arr2)


_____In 1D_____


-----Array 1-----
[12 23 45 55]


-----Array 2-----
[10  1  3 55]


-----Concatenated Array-----


_____Sum Of Arrays'_____
[ 22  24  48 110]


_____In 2D_____


-----Array 1-----
[[12 23 45 55]
 [10  1  3 55]]


-----Array 2-----
[[ 1  2  3  4]
 [11 34 32  8]]


-----Concatenated Array-----


[[12 23 45 55]
 [10  1  3 55]
 [ 1  2  3  4]
 [11 34 32  8]]


_____Sum Of Arrays'_____
[[13 25 48 59]
 [21 35 35 63]]
