----> List [ 1D , 2D ]

----> Numpy Array [ 1D , 2D ]




In [ ]:
import numpy as np

#List
print('\n')
print("-----1-D List-----")
print('\n')

L = [10,20,30] #1D
print(L)

print('\n')
print("-----1-D Array-----")
print('\n')

#array 1D
arr = np.array(L)
print(arr)



#List
print('\n')
print("-----2-D List-----")
print('\n')

L = [[10,20,30],[40,50,60]] #2D
print(L)
print('\n')
print("__________")
print('\n')
print(L[0])
print('\n')
print("__________")
print('\n')
print(L[0][1]) #Element at 1 index in 1st row of 2D List


#array 2D
print('\n')
print("-----2-D Array-----")
print('\n')

arr = np.array([[19,33,44],[22,34,69]])
print(arr)
print('\n')
print("__________")
print('\n')
print(arr[0])

print(arr)
print('\n')
print("__________")
print('\n')
print(arr[1][1]) #Element at 1 index in 1st row of 2D Array









-----1-D List-----


[10, 20, 30]


-----1-D Array-----


[10 20 30]


-----2-D List-----


[[10, 20, 30], [40, 50, 60]]


__________


[10, 20, 30]


__________


20


-----2-D Array-----


[[19 33 44]
 [22 34 69]]


__________


[19 33 44]
[[19 33 44]
 [22 34 69]]


__________


34


Question --> Insert 100 At place of 4

In [ ]:
#List
print('\n')
print("-----List Case-----")
print('\n')
L = [[1,2,3],[4,5,6]]
L[1].insert(0,100)
print(L)



import numpy as np
#Array
print('\n')
print("-----Array Case-----")
print('\n')
arr = np.array([[1,2,3],[4,5,6]])
arr = np.insert(arr, 0, 100, axis=1)

print(arr)

# in list inserting 100 only at specific place is possible , but in array the size must remain same for both rows and columns. so,that's why insertion of only 100
# is not possible in array. so, to make it work we need to add elements in both row and column



-----List Case-----


[[1, 2, 3], [100, 4, 5, 6]]


-----Array Case-----


[[100   1   2   3]
 [100   4   5   6]]


In [ ]:
#List
print('\n')
print("-----List Case-----")
print('\n')
L = [1,2,3]
Lm = L*2
print(Lm)

#Array
print('\n')
print("-----Array Case-----")
print('\n')
arr = np.array([12,11,33])
arrM = arr*2
print(arrM)





-----List Case-----


[1, 2, 3, 1, 2, 3]


-----Array Case-----


[24 22 66]


In [ ]:
#Comparison
#List
import time

start = time.time()
l = [i*2 for i in range(10000000)]

print("List Output :",time.time()-start)

#Array
import numpy as np

start = time.time()
arr = np.array(10000000)
arrM = arr*2

print("Array Output :",time.time()-start)



print('\n')
print("__________")
print('\n')
print("Conclusion :-")
print("List Works Slower Than Array")

List Output : 2.278073787689209
Array Output : 0.0003898143768310547


__________


Conclusion :-
List Works Slower Than Array


#Zero's In Python





In [ ]:
#zero's array in 1D
import numpy as np
print("Zero's Array In 1D")
arr = np.zeros(5)
print(arr)
print('\n')
#zero's array in 2D
print("Zero's Array In 2D")
arr = np.zeros((2,3))
print(arr)

#zero's array in 3D
print('\n')
print("Zero's Array In 3D")
arr = np.zeros(((2,3,4)))
print(arr)




Zero's Array In 1D
[0. 0. 0. 0. 0.]


Zero's Array In 2D
[[0. 0. 0.]
 [0. 0. 0.]]


Zero's Array In 3D
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


#One's In Python

In [ ]:
#one's array in 1D
import numpy as np
print("--One's Array In 1D--")
arr = np.ones(5)
print(arr)
print('\n')
#one's array in 2D
print("--One's Array In 2D--")
arr = np.ones((2,3))
print(arr)

#one's array in 3D
print('\n')
print("--One's Array In 3D--")

arr = np.ones(((2,3,4)))
print(arr)

--One's Array In 1D--
[1. 1. 1. 1. 1.]


--One's Array In 2D--
[[1. 1. 1.]
 [1. 1. 1.]]


--One's Array In 3D--
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Question --> Make A Zero's Array And Replace Elements With '10' (2D Array)

In [ ]:
import numpy as np
arr = np.zeros((2,3))
arr += 10
print(arr)


[[10. 10. 10.]
 [10. 10. 10.]]


Question --> Make A Ones's Array And Replace Elements With '5' (2D Array)

In [ ]:
import numpy as np
arr = np.ones((2,3))
arr *= 5
print(arr)

[[5. 5. 5.]
 [5. 5. 5.]]


#Full In Python

In [ ]:
#full for 1D
import numpy as np
arr = np.full((2),10) #1-D
print("--1-D Array Using Full--")
print(arr)
print('\n')

#full for 2D
arr = np.full((2,3),10) #2-D
print("--2-D Array Using Full--")
print(arr)
print('\n')

#full for 3D
arr = np.full((2,3,4),10) #3-D
print("--3-D Array Using Full--")
print(arr)

--1-D Array Using Full--
[10 10]


--2-D Array Using Full--
[[10 10 10]
 [10 10 10]]


--3-D Array Using Full--
[[[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]

 [[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]]


#Random In Python

In [ ]:
import numpy as np
print("--1-D Array--")
arr = np.random.random(5)
print(arr)

print('\n')
print("--2-D Array--")
arr = np.random.random((2,3))
print(arr)

print('\n')
print("--3-D Array--")
arr = np.random.random((2,3,4))
print(arr)

--1-D Array--
[0.84159617 0.82323767 0.79930594 0.27958293 0.85895093]


--2-D Array--
[[0.45333459 0.32985626 0.7310928 ]
 [0.02628896 0.80829578 0.97300358]]


--3-D Array--
[[[6.55881283e-01 2.86140704e-01 3.55985250e-01 7.68741822e-01]
  [7.88154369e-01 7.44220418e-01 2.80195253e-01 8.77909177e-01]
  [1.66629888e-01 5.50599649e-03 1.33972005e-01 6.52991542e-04]]

 [[7.08894444e-01 3.77372316e-01 3.43202290e-01 3.08331473e-01]
  [6.70067327e-01 8.93579306e-01 4.19769904e-02 2.62062631e-01]
  [5.16744524e-02 2.96191313e-01 2.22022717e-01 9.58123225e-03]]]


#Arange In Python

In [ ]:
import numpy as np
print("1D")
arr = np.arange(6)
print(arr)

print('\n')
print("2D")
arr = np.arange(6).reshape(2, 3)
print(arr)

1D
[0 1 2 3 4 5]


2D
[[0 1 2]
 [3 4 5]]


# Vector , Matrix And Tensor


In [ ]:
#vector (List)
print("__________VECTOR (LIST)__________")
print("----------1D List----------")
L = [10,20,30]
print(L)
print("----------2D List----------")
L = [10,20,8],[88,88,23]
print(L)
print("----------3D List----------")
L = [20,22,33],[34,45,56],[76,54,21]
print(L)

#vector (Array)
print('\n')
print("__________VECTOR (ARRAY)__________")
print("----------1D Array----------")
import numpy as np
arr = np.array([11,22,33])
print(arr)
print("----------2D Array----------")
arr = np.array([[12,44,44] , [22,90,88]])
print(arr)
print("----------3D Array----------")
arr = np.array([[10,20,30],[22,21,32],[21,21,21]])
print(arr)


__________VECTOR (LIST)__________
----------1D List----------
[10, 20, 30]
----------2D List----------
([10, 20, 8], [88, 88, 23])
----------3D List----------
([20, 22, 33], [34, 45, 56], [76, 54, 21])


__________VECTOR (ARRAY)__________
----------1D Array----------
[11 22 33]
----------2D Array----------
[[12 44 44]
 [22 90 88]]
----------3D Array----------
[[10 20 30]
 [22 21 32]
 [21 21 21]]


In [ ]:
#array
import numpy as np
arr = np.arange(11).reshape(11,1)
print(arr)
print("Shape : " , np.shape(arr))
print("Size : " , np.size(arr))
print("Dimension : " , np.ndim(arr))
print("Data Type : " , arr.dtype)



[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
Shape :  (11, 1)
Size :  11
Dimension :  2
Data Type :  int64
