Array Reshaping
 1. Reshape()
 2. Flatten() -> Create Copy
 3. Revel() -> Return Original
 4. Transpose

In [ ]:
#reshape()
import numpy as np
print("---Reshape---")
arr = np.arange(12)
up_arr = np.reshape (arr, (3,4)) #2D
print(up_arr)

#example

print('\n')
print("----example----")

arr = np.arange(24)
up_arr = np.reshape (arr, (2,3,4)) #3D
print(up_arr)

print('\n')
print("____________________")
print('\n')

#flatten() -> Creates A Copy And Than Works Upon It
print('\n')
print("---Flatten---")

arr = np.arange(12).reshape(3,4) #2D
up_arr = arr.flatten() #2D -> 1D
print(up_arr)

#example
print('\n')
print("---example---")
arr = np.arange(24).reshape(2,3,4) #3D
up_arr = arr.flatten() #3D -> 1D
print(up_arr)

print('\n')
print("____________________")
print('\n')

#revel() -> Works On Original Array
print('\n')
print("---Revel---")
arr1 = np.arange(12).reshape(3,4) #2D
up_arr = arr1.ravel() #2D -> 1D
print(up_arr)

#example
print('\n')
print("---example---")
arr1 = np.arange(32).reshape(2,4,4) #3D
up_arr = arr1.ravel() #3D -> 1D
print(up_arr)

print('\n')
print("____________________")
print('\n')


#transpose -> Converts Rows To Column
print('\n')
print("---Transpose---")
arr1 = np.arange(12).reshape(3,4) #2D
up_arr = arr1.transpose()
print(up_arr)

#example
print('\n')
print("---example---")
arr2 = np.arange(24).reshape(2,3,4) #3D
up_arr = arr2.transpose()
print(up_arr)


---Reshape---
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


----example----
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


____________________




---Flatten---
[ 0  1  2  3  4  5  6  7  8  9 10 11]


---example---
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


____________________




---Revel---
[ 0  1  2  3  4  5  6  7  8  9 10 11]


---example---
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


____________________




---Transpose---
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


---example---
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


Slicing In Array

In [ ]:
import numpy as np

#slicing for 1d
print("--Slicing in 1D--")
arr = np.arange(10)
print(arr[5:8])

print('\n')
print("____________________")
print('\n')


#Slicing for 2D
print("--Slicing in 2D--")
arr1 = np.arange(12).reshape(3,4)
print(arr1[1:3,1:3])

print('\n')
print("____________________")
print('\n')


#Slicing for 3D
print("--Slicing in 3D--")
arr2 = np.arange(24).reshape(3,4,2)
print(arr2)
print("---------")
print(arr2[0:1,0:1,0:1])
print(arr2[2:,3:,1:])




--Slicing in 1D--
[5 6 7]


____________________


--Slicing in 2D--
[[ 5  6]
 [ 9 10]]


____________________


--Slicing in 3D--
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
---------
[[[0]]]
[[[23]]]


Looping In Numpy
1. while
2. for

In [ ]:
#while for 1D
import numpy as np
print("---While Loop In 1D Array---")
arr = np.arange(12)
i = 0
while i < arr.size:
  print(arr[i] , "" , end = "")
  i = i+1

print('\n')
print("__________")
print('\n')

#while for 2D
print('\n')
print("---While Loop In 2D Array---")
arr = np.arange(12).reshape(3,4)
i = 0
j = 0
while i < len(arr):
  while j < len(arr[i]):
    print(arr[i][j] , "" , end = "")
    j = j+1
  print()
  i = i+1
  j = 0


print('\n')
print("__________")
print('\n')


#while for 3D
print('\n')
print("---While Loop In 3D Array---")
arr = np.arange(24).reshape(2,3,4)
i = 0
while i < len(arr):
    j = 0
    while j < len(arr[i]):
        k = 0
        while k < len(arr[i][j]):
            print(arr[i][j][k], end=" ")
            k += 1
        j += 1
        print()


    i += 1
    print()



---While Loop In 1D Array---
0 1 2 3 4 5 6 7 8 9 10 11 

__________




---While Loop In 2D Array---
0 1 2 3 
4 5 6 7 
8 9 10 11 


__________




---While Loop In 3D Array---
0 1 2 3 
4 5 6 7 
8 9 10 11 

12 13 14 15 
16 17 18 19 
20 21 22 23 



In [11]:
#for loop for 1D
import numpy as np
print("---For Loop In 1D Array---")
arr = np.arange(12)
for i in arr:
  print(i , "" , end = "")

print('\n')
print("__________")
print('\n')

#for loop for 2D
print("---For Loop In 2D Array---")
arr = np.arange(12).reshape(3,4)
for i in arr:
  for j in i:
    print(j , "" , end = "")
  print()

print('\n')
print("__________")
print('\n')

#for loop for 3D
print("---For Loop In 3D Array---")
arr = np.arange(24).reshape(2,3,4)
for i in arr:
    for j in i:
        for k in j:
            print(k, end=" ")

        print()

    print()

---For Loop In 1D Array---
0 1 2 3 4 5 6 7 8 9 10 11 

__________


---For Loop In 2D Array---
0 1 2 3 
4 5 6 7 
8 9 10 11 


__________


---For Loop In 3D Array---
0 1 2 3 
4 5 6 7 
8 9 10 11 

12 13 14 15 
16 17 18 19 
20 21 22 23 

