Numpy
#vscode setup
1. python -m venv venv(folder name)[venv --> virtual environment]
2. ./venv/scripts/activate.bat (activating the venv)
3. pip install numpy
4. python file.py(ex - mawa.py)
5. "deactivate" to exit the venv (deactivating)


In [ ]:
import numpy
#import numpy as np
#from numpy import arange
#from numpy import *

print('\n')
print("-----Example No. --> 1-----")
print('\n')
#example no. --> 1
n = numpy.arange(11)
print(type(n))
print(n)
print(n[0])

print('\n')
print("-----Example No. --> 2-----")
print('\n')


#example no. --> 2
n = numpy.arange(12)
o = n.reshape(3,4) #3 -> rows and 4 -> columns
print(type(o))
print(o)


print('\n')
print("-----Example No. --> 3-----")
print('\n')

#example no. --> 3
n = numpy.arange(12).reshape(3,4)
print(n)

#example no. --> 4
print('\n')
print("-----Example No. --> 4-----")
print('\n')

n = numpy.arange(24).reshape(3,4,2)
print(n)


#example no. --> 5(spliting)
print('\n')
print("-----Example No. --> 5-----")
print('\n')
n = numpy.arange(12).reshape(4,3)
print("Before Splitting")
print('\n')
print(n)
print('\n')

print("After Splitting")
print('\n')
print(n[0:4,2])


#Alternative methods
# print(n[:,-1])
# print(n[:,2])









-----Example No. --> 1-----


<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10]
0


-----Example No. --> 2-----


<class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


-----Example No. --> 3-----


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


-----Example No. --> 4-----


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


-----Example No. --> 5-----


Before Splitting


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


After Splitting


[ 2  5  8 11]


Question --> Print Only 4 And 7 From The Matrix

In [ ]:
import numpy

n = numpy.arange(12).reshape(4,3)
print(n)
print('\n')
print("----------Output----------")
print('\n')
print(n[1:3,1])


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
----------Output----------
[4 7]
